In [1]:
import pandas as pd

In [2]:
# To load the dataset using pandas

df = pd.read_csv("C:/Users/USER MICHAEL$$/Downloads/customer_purchase_pattern.csv")

In [3]:
# to get the first 5 rows of each column
df.head()

,Customer ID,Age,Gender,Purchased Items,Category,Purchase Amount (USD),Location,Size,Color,Period,Rating score,Membership Status,Shipping Method,Discount Used,Promo Code Applied,Previous Purchases,Payment Type,Purchase Frequency
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Shipping Type,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Shipping Type,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Shipping Type,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Shipping Type,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Shipping Type,Yes,Yes,31,PayPal,Annually

In [4]:
# To know the data structure 

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2698 entries, 0 to 2697
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer ID            2698 non-null   int64
 1   Age                    2698 non-null   int64
 2   Gender                 2698 non-null   object
 3   Purchased Items        2698 non-null   object
 4   Category               2698 non-null   object
 5   Purchase Amount (USD)  2698 non-null   int64
 6   Location               2698 non-null   object
 7   Size                   2698 non-null   object
 8   Color                  2698 non-null   object
 9   Period                 2698 non-null   object
 10  Rating score           2661 non-null   float64
 11  Membership Status      2698 non-null   object
 12  Shipping Method        2698 non-null   object
 13  Discount Used          2698 non-null   object
 14  Promo Code Applied     2698 non-null   object
 15  Previous Purchases     2698 non-null   int64
 16  Payment Type           2698 non-null   object
 17  Purchase Frequency     2698 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 379.5+ KB

In [5]:
# summary statistics of the dataset
df.describe(include= 'all')

,Customer ID,Age,Gender,Purchased Items,Category,Purchase Amount (USD),Location,Size,Color,Period,Rating score,Membership Status,Shipping Method,Discount Used,Promo Code Applied,Previous Purchases,Payment Type,Purchase Frequency
count,2698.000000,2698.000000,2698,2698,2698,2698.000000,2698,2698,2698,2698,2661.00000,2698,2698,2698,2698,2698.000000,2698,2698
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,1,2,2,NaN,6,7
top,NaN,NaN,Male,Pants,Clothing,NaN,California,M,Olive,Spring,NaN,No,Shipping Type,Yes,Yes,NaN,Cash,Every 3 Months
freq,NaN,NaN,2652,125,1198,NaN,66,1185,123,694,NaN,1645,2698,1677,1677,NaN,468,406
mean,1349.500000,44.108599,NaN,NaN,NaN,59.474426,NaN,NaN,NaN,NaN,3.75419,NaN,NaN,NaN,NaN,25.686805,NaN,NaN
std,778.989837,15.301387,NaN,NaN,NaN,23.826626,NaN,NaN,NaN,NaN,0.71548,NaN,NaN,NaN,NaN,14.384857,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.50000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,675.250000,31.000000,NaN,NaN,NaN,38.000000,NaN,NaN,NaN,NaN,3.10000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1349.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.80000,NaN,NaN,NaN,NaN,26.000000,NaN,NaN
75%,2023.750000,57.000000,NaN,NaN,NaN,80.000000,NaN,NaN,NaN,NaN,4.40000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,2698.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.00000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [6]:
# checking null values

df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Purchased Items           0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Period                    0
Rating score             37
Membership Status         0
Shipping Method           0
Discount Used             0
Promo Code Applied        0
Previous Purchases        0
Payment Type              0
Purchase Frequency        0
dtype: int64

In [7]:
# To find the median and replace it with the missing value within each category
df['Rating score'] =df.groupby('Category')['Rating score'].transform(lambda x: x.fillna(x.median()))

In [8]:
# checking the null values again

df.isnull().sum()

Customer ID              0
Age                      0
Gender                   0
Purchased Items          0
Category                 0
Purchase Amount (USD)    0
Location                 0
Size                     0
Color                    0
Period                   0
Rating score             0
Membership Status        0
Shipping Method          0
Discount Used            0
Promo Code Applied       0
Previous Purchases       0
Payment Type             0
Purchase Frequency       0
dtype: int64

In [9]:
# changing all the columns to snake_case 

df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df=df.rename(columns={'purchase_amount_(usd)':'amount_spent'})

In [10]:
# check the columns

df.columns

Index(['customer_id', 'age', 'gender', 'purchased_items', 'category',
       'amount_spent', 'location', 'size', 'color', 'period', 'rating_score',
       'membership_status', 'shipping_method', 'discount_used',
       'promo_code_applied', 'previous_purchases', 'payment_type',
       'purchase_frequency'],
      dtype='object')

In [11]:
# create age_bracket

labels = ['teenager', 'adult', 'mature_adult', 'senior']
df['age_bracket']= pd.qcut(df['age'], q= 4, labels = labels)

In [12]:
df[['age', 'age_bracket']].head()

   age   age_bracket
0   55  mature_adult
1   19      teenager
2   50  mature_adult
3   21      teenager
4   45  mature_adult

In [13]:
# create another column frequency_purchase_days

mapping_frequency = {
    'Weekly': 7,
    'Bi_Weekly': 14,
    'Every 3 Months': 90,
    'Monthly': 30,
    'Quarterly': 90,
    'Fortnightly': 14,
    'Annually': 365
}
df['frequency_purchase_days'] = df['purchase_frequency'].map(mapping_frequency)

In [14]:
df[['purchase_frequency','frequency_purchase_days']].head(10)

  purchase_frequency  frequency_purchase_days
0        Fortnightly                     14.0
1        Fortnightly                     14.0
2             Weekly                      7.0
3             Weekly                      7.0
4           Annually                    365.0
5             Weekly                      7.0
6          Quarterly                     90.0
7             Weekly                      7.0
8           Annually                    365.0
9          Quarterly                     90.0

In [15]:
df[['discount_used', 'promo_code_applied']].head()

  discount_used promo_code_applied
0           Yes                Yes
1           Yes                Yes
2           Yes                Yes
3           Yes                Yes
4           Yes                Yes

In [16]:
(df['discount_used'] == df['promo_code_applied']).all()

np.True_

In [17]:
# since both discount_used and promo_code_applied have same data, lets drop one of them

df = df.drop('promo_code_applied', axis =1)

In [18]:
# promo_code_applied dropped

df.columns

Index(['customer_id', 'age', 'gender', 'purchased_items', 'category',
       'amount_spent', 'location', 'size', 'color', 'period', 'rating_score',
       'membership_status', 'shipping_method', 'discount_used',
       'previous_purchases', 'payment_type', 'purchase_frequency',
       'age_bracket', 'frequency_purchase_days'],
      dtype='object')

In [24]:
import psycopg2
import sqlalchemy

In [25]:
!pip install psycopg2 sqlalchemy

Requirement already satisfied: psycopg2 in c:\users\user michael$$\appdata\local\programs\python\python311\lib\site-packages (2.9.11)
Requirement already satisfied: sqlalchemy in c:\users\user michael$$\appdata\local\programs\python\python311\lib\site-packages (2.0.44)
Requirement already satisfied: greenlet>=1 in c:\users\user michael$$\appdata\local\programs\python\python311\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\user michael$$\appdata\local\programs\python\python311\lib\site-packages (from sqlalchemy) (4.15.0)

In [28]:
from sqlalchemy import create_engine

# Step 1: Connect to PostgreSQL
# Replace placeholders with your actual details
username = "postgres"      # default user
password = "sa" # the password you set during installation
host = "localhost"         # if running locally
port = "5432"              # default PostgreSQL port
database = "customer_pattern"    # the database you created in pgAdmin

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load DataFrame into PostgreSQL
table_name = "customer_purchase_pattern"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'customer_purchase_pattern' in database 'customer_pattern'.